# Generated by Django 5.2.4 on 2025-07-21 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_emailaccount_emailtemplate_processedemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
